# -*- coding: utf-8 -*-
"""Spam Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HP5bMy7uDfqRSRrdvk7Z8LiS8m9dtHql
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import pickle

import pandas as pd
import numpy as np

df = pd.read_csv("/content/spam_detection_dataset.csv", encoding='latin-1')

df.head()

df.shape

df.info()

df.columns

"""Statistics"""

df.describe()

"""Check Missing Values"""

df.isnull().sum()

df['is_spam'].value_counts()

"""Visualization"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='is_spam', data=df)

plt.title("Spam vs Not Spam")
plt.show()

"""Correlation Analysis"""

corr = df.corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr,
            annot=True,
            cmap='coolwarm')

plt.show()

"""Distribution of Numerical Features"""

sns.histplot(df['num_links'], kde=True)

plt.title("Distribution of Links")
plt.show()

sns.histplot(df['num_words'], kde=True)

plt.title("Distribution of Words")
plt.show()

sns.histplot(df['sender_score'], kde=True)

plt.title("Sender Score Distribution")
plt.show()

sns.boxplot(
    x='is_spam',
    y='num_links',
    data=df
)

plt.show()

sns.boxplot(
    x='is_spam',
    y='num_words',
    data=df
)

plt.show()

sns.boxplot(
    x='is_spam',
    y='sender_score',
    data=df
)

plt.show()

"""Define Features and Target"""

X = df.drop('is_spam', axis=1)

y = df['is_spam']

X.head()

y.head()

"""Train-Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Check Shapes









"""

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

X_train.head()

X_test.head()

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred[:10])

comparison = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})

comparison.head(10)

print("Model Trained Successfully")

"""Accuracy Score"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""Classification Report"""

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred
))

train_accuracy = model.score(
    X_train,
    y_train
)

print("Training Accuracy:", train_accuracy)

test_accuracy = model.score(
    X_test,
    y_test
)

print("Testing Accuracy:", test_accuracy)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

"""Decision Tree"""

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

from sklearn.metrics import accuracy_score

print("Decision Tree Accuracy:",
      accuracy_score(y_test, dt_pred))

"""Random Forest"""

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("Random Forest Accuracy:",
      accuracy_score(y_test, rf_pred))

"""KNN"""

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

print("KNN Accuracy:",
      accuracy_score(y_test, knn_pred))

results = pd.DataFrame({
    'Model':[
        'Logistic Regression',
        'Decision Tree',
        'Random Forest',
        'KNN'
    ],
    'Accuracy':[
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, dt_pred),
        accuracy_score(y_test, rf_pred),
        accuracy_score(y_test, knn_pred)
    ]
})

print(results)

import pickle

pickle.dump(
    rf,
    open("spam_model.pkl", "wb")
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

pickle.dump(
    scaler,
    open("scaler.pkl", "wb")
)

import os

print(os.listdir())

loaded_model = pickle.load(
    open("spam_model.pkl", "rb")
)

loaded_scaler = pickle.load(
    open("scaler.pkl", "rb")
)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

import pickle

pickle.dump(rf, open("spam_model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))

print(type(X_train))

!pip install streamlit

import streamlit as st
import pickle
import pandas as pd

# Load Model
model = pickle.load(open("spam_model.pkl", "rb"))

# Load Scaler
scaler = pickle.load(open("scaler.pkl", "rb"))

st.title("📩 Spam Detection System")

st.write("Enter message features below")

# User Inputs

num_links = st.number_input(
    "Number of Links",
    min_value=0
)

num_words = st.number_input(
    "Number of Words",
    min_value=0
)

has_offer = st.selectbox(
    "Contains Offer?",
    [0, 1]
)

sender_score = st.number_input(
    "Sender Score",
    min_value=0.0,
    max_value=1.0,
    value=0.5
)

all_caps = st.selectbox(
    "All Caps Message?",
    [0, 1]
)

# Predict Button

if st.button("Predict"):

    data = pd.DataFrame([[
        num_links,
        num_words,
        has_offer,
        sender_score,
        all_caps
    ]], columns=[
        'num_links',
        'num_words',
        'has_offer',
        'sender_score',
        'all_caps'
    ])

    data_scaled = scaler.transform(data)

    prediction = model.predict(data_scaled)

    if prediction[0] == 1:
        st.error("🚨 Spam Message")
    else:
        st.success("✅ Not Spam")

!pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.title("Spam Detection App")
# 
# st.write("Hello from Streamlit!")

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt &

!curl ipv4.icanhazip.com